name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt
          
      - name: Run tests
        run: |
          python -m pytest --cov=. --cov-report=xml:./pytest.xml --junit-xml=./pytest-results.xml tests

      - name: Pytest Coverage Comment
        uses: MishaKav/pytest-coverage-comment@v1.1.47
        with:
          pytest-coverage-path: ./pytest.xml
          junitxml-path: ./pytest-results.xml
          title: My Coverage Report Title
          badge-title: My Badge Coverage Title